version: '3.4'

services:
  recipeportal_sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  recipeportal_redis:
    image: redis

  recipeportal_rabbitmq:
    image: rabbitmq:3-management

  recipeportal_api:
    image: ${DOCKER_REGISTRY-}recipeportalapi
    build:
      context: .
      dockerfile: System/RecipePortal.API/Dockerfile
    depends_on:
      - recipeportal_sqlserver
      - recipeportal_redis
      - recipeportal_rabbitmq

  recipeportal_identity:
    image: ${DOCKER_REGISTRY-}recipeportalidentity
    build:
      context: .
      dockerfile: System/RecipePortal.Identity/Dockerfile
    depends_on:
      - recipeportal_sqlserver
      - recipeportal_redis
      - recipeportal_rabbitmq

  recipeportal_worker:
    image: ${DOCKER_REGISTRY-}recipeportalworker
    build:
      context: .
      dockerfile: System/RecipePortal.Worker/Dockerfile
    depends_on:
      - recipeportal_sqlserver
      - recipeportal_redis
      - recipeportal_rabbitmq

  recipeportal_web:
    image: ${DOCKER_REGISTRY-}recipeportalweb
    build:
      context: .
      dockerfile: System/RecipePortal.Web/Dockerfile
    depends_on:
      - recipeportal_sqlserver
      - recipeportal_redis
      - recipeportal_rabbitmq

