version: '3.4'

services:
  recipeportal_sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
      - MSSQL_PID=Express
    ports:
      - "21433:1433"
    networks:
      - shared-recipeportal-net
    #volumes:      
      #- sqlserver-data:/var/opt/mssql

  recipeportal_api:
    ports:
      - "21430:80"
    networks:
      - shared-recipeportal-net
    env_file:
      - env.api 

  recipeportal_identity:
    ports:
      - "21431:80"
    networks:
      - shared-recipeportal-net
    env_file:
      - env.identity

#volumes:
  #sqlserver-data:

networks:
  shared-recipeportal-net:
    name: RecipePortal
    driver: bridge
